@startuml 基本のフロー

start

:課題発生;

repeat
    :解決のための情報を集める
    (技術情報、スコープ、納期);
repeat while (情報は十分か)

:課題解決のプロトタイプを作成する
(e.g ソフトを書く、ドキュメントに目を通す、
build にトライする等);

if (自己解決は有限時間内に完了する見込みかを判断する) then (yes)
    :そのまま作業を進める;
else (no)
    :なぜ有限時間内に完了しないかの
     理由を説明できるようにする;
    :有限時間内の解決できるように共同作業者に支援してもらう
     or 期限を延ばせるように交渉する;
endif

:課題解決;

end

@enduml